[build]
builder = "DOCKERFILE"
dockerfilePath = "backend-spring/Dockerfile"
watchPatterns = ["backend-spring/**"]

[deploy]
healthcheckPath = "/api/restaurants"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
